accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import RegisterView, ProfileView, CustomLogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
]

main/urls.py
# main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

neurrehab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  # Подключение маршрутов главной страницы
    path('accounts/', include('accounts.urls')),  # Маршрутизация для аккаунтов
    path('tasks/', include('tasks.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
# tasks/urls.py
from django.urls import path
from . import views
from .views import TaskListView, TaskDetailView, ProfileStatisticsView, auto_task, image_match_auto

app_name = 'tasks'

urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('<str:category>/<str:task_type>/', TaskDetailView.as_view(), name='task_detail'),
    path('statistics/', ProfileStatisticsView.as_view(), name='profile_statistics'),
    path('auto/', auto_task, name='auto_task'),
    path('fruits/image_match/auto/', image_match_auto, name='image_match_auto'),
    path('admin/get_words_without_images/', views.get_words_without_images, name='get_words_without_images'),
    path('<task_type>/none/', TaskDetailView.as_view(), name='task_detail_no_category'),  # Для action_description без категории
]

accounts/models.py
# accounts/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager

class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('patient', 'Пациент'),
        ('specialist', 'Специалист'),
        ('admin', 'Администратор'),
    )

    username = None  # Удаляем поле username
    email = models.EmailField(_('email address'), unique=True)  # Уникальное поле email
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='patient')
    first_name = models.CharField(_('Имя'), max_length=30)
    last_name = models.CharField(_('Фамилия'), max_length=30)
    middle_name = models.CharField(_('Отчество'), max_length=30, blank=True, null=True)
    birth_date = models.DateField(_('Дата рождения'), blank=True, null=True)
    phone_number = models.CharField(_('Телефон'), max_length=15, blank=True, null=True)
    country = models.CharField(_('Страна'), max_length=50, blank=True, null=True)
    city = models.CharField(_('Город'), max_length=50, blank=True, null=True)
    specialization = models.CharField(_('Специализация'), max_length=100, blank=True, null=True)
    experience = models.TextField(_('Опыт'), blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    email_notifications = models.BooleanField(_('Email уведомления'), default=True)
    sms_notifications = models.BooleanField(_('SMS уведомления'), default=False)

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',  # Измените related_name
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
        related_query_name='user',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_set',  # Измените related_name
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_query_name='user',
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class PatientRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'email': _('Электронная почта'),
            'password1': _('Пароль'),
            'password2': _('Подтверждение пароля'),
        }


class SpecialistRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'middle_name', 'email', 'phone_number', 'specialization', 'experience', 'password1', 'password2')
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'middle_name': _('Отчество'),
            'email': _('Электронная почта'),
            'phone_number': _('Телефон'),
            'specialization': _('Специализация'),
            'experience': _('Опыт'),
            'password1': _('Пароль'),
            'password2': _('Подтверждение пароля'),
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'middle_name', 'birth_date', 'phone_number', 'country', 'city', 'avatar')
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'middle_name': _('Отчество'),
            'birth_date': _('Дата рождения'),
            'phone_number': _('Телефон'),
            'country': _('Страна'),
            'city': _('Город'),
            'avatar': _('Аватар'),
            'email_notifications': _('Email уведомления'),
            'sms_notifications': _('SMS уведомления'),
        }

accounts/views.py
# accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.views import View
from .forms import PatientRegistrationForm, SpecialistRegistrationForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib.auth import logout

class RegisterView(View):
    def get(self, request):
        patient_form = PatientRegistrationForm()
        specialist_form = SpecialistRegistrationForm()
        return render(request, 'accounts/register.html',
                      {'patient_form': patient_form, 'specialist_form': specialist_form})

    def post(self, request):
        if 'patient' in request.POST:
            form = PatientRegistrationForm(request.POST)
        else:
            form = SpecialistRegistrationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.role = 'patient' if isinstance(form, PatientRegistrationForm) else 'specialist'
            user.save()
            login(request, user)
            return redirect('profile')
        patient_form = PatientRegistrationForm() if isinstance(form, SpecialistRegistrationForm) else form
        specialist_form = SpecialistRegistrationForm() if isinstance(form, PatientRegistrationForm) else form
        return render(request, 'accounts/register.html',
                      {'patient_form': patient_form, 'specialist_form': specialist_form})


class ProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = ProfileUpdateForm(instance=request.user)
        return render(request, 'accounts/profile.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
        return render(request, 'accounts/profile.html', {'form': form})


class CustomLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('home')  # Перенаправление после выхода

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<style>
    .card {
        background-color: #fff !important; /* Белый фон для карточки */
        color: #000 !important; /* Черный текст для карточки */
    }

    .card-header {
       /* background-color: #007bff !important; Цвет заголовка карточки */
        color: #000 !important; /* Белый текст для заголовка */
    }

    .form-control {
        background-color: #f8f9fa !important; /* Фон для элементов формы */
        color: #495057 !important;
    }

    .btn-primary {
        background-color: #007bff !important;
        border-color: #007bff !important;
    }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Войти</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% if next %}
                            <input type="hidden" name="next" value="{{ next }}">
                        {% endif %}
                        <div class="form-group">
                            <label for="id_login">Электронная почта:</label>
                            <input type="text" name="username" required id="id_login" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_password">Пароль:</label>
                            <input type="password" name="password" required id="id_password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block mt-3">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container">
    <h2>Выход выполнен успешно</h2>
  </div>
{% endblock %}

accounts/templates/accounts/password_change.html
<!-- accounts/templates/accounts/password_change.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h2>Смена пароля</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить пароль</button>
  </form>
{% endblock %}

accounts/templates/accounts/password_change_done.html
<!-- accounts/templates/accounts/password_change_done.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h2>Пароль изменен</h2>
  <p>Ваш пароль был успешно изменен.</p>
{% endblock %}

accounts/templates/accounts/profile.html
<!-- accounts/templates/accounts/profile.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
/* Встроенные стили для профиля */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f9f9f9;
    margin: 0;
    padding: 0;
}

.profile-container {
    display: flex;
    max-width: 1200px;
    margin: 50px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.sidebar {
    width: 200px;
    padding: 20px;
    background-color: #f4f4f4;
    border-right: 1px solid #ddd;
}

.sidebar a {
    display: block;
    padding: 10px;
    text-decoration: none;
    color: black;
    margin-bottom: 10px;
    border-radius: 5px;
    transition: background-color 0.3s ease;
}

.sidebar a:hover {
    background-color: #ddd;
}

.profile-content {
    flex-grow: 1;
    padding: 20px;
}

.profile-header {
    display: flex;
    align-items: center;
    margin-bottom: 20px;
}

.profile-header img {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    object-fit: cover;
    margin-right: 20px;
}

.profile-header .profile-info {
    flex-grow: 1;
}

.profile-header .profile-info h2 {
    margin: 0;
    color: #333;
}

.profile-header .profile-info p {
    margin: 5px 0;
    color: #666;
}

.profile-form {
    display: flex;
    flex-direction: column;
}

.profile-form input[type="text"],
.profile-form input[type="email"],
.profile-form input[type="password"],
.profile-form input[type="date"],
.profile-form input[type="file"],
.profile-form select,
.profile-form textarea {
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.profile-form button {
    padding: 10px;
    background-color: #4CAF50;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.profile-form button:hover {
    background-color: #45a049;
}

.change-password-link {
    display: inline-block;
    margin-top: 15px;
    padding: 10px 20px;
    background-color: #007BFF;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s ease;
}

.change-password-link:hover {
    background-color: #0056b3;
}

@media (max-width: 600px) {
    .profile-container {
        flex-direction: column;
        margin: 20px;
        padding: 15px;
    }

    .profile-header {
        flex-direction: column;
        align-items: center;
    }

    .profile-header img {
        margin-bottom: 10px;
    }

    .profile-header .profile-info {
        text-align: center;
    }
}
</style>

<div class="profile-container">
    <div class="sidebar">
        <a href="{% url 'profile' %}">Профиль</a>
        <a href="{% url 'tasks:task_list' %}">Список заданий</a>
        <a href="{% url 'tasks:profile_statistics' %}" class="btn btn-primary">Посмотреть статистику</a>
        <!-- Другие ссылки можно добавить здесь -->
    </div>
    <div class="profile-content">
        <div class="profile-header">
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Аватар пользователя">
            {% else %}
                <img src="{% static 'default-avatar.png' %}" alt="Аватар по умолчанию">
            {% endif %}
            <div class="profile-info">
                <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                <p>{{ user.email }}</p>
            </div>
        </div>
        <form method="post" enctype="multipart/form-data" class="profile-form">
            {% csrf_token %}

            {{ form.non_field_errors }}

            <!-- Вручную отображаем поля формы -->
            <div class="form-group">
                {{ form.first_name.label_tag }} {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name.label_tag }} {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.middle_name.label_tag }} {{ form.middle_name }}
            </div>
            <div class="form-group">
                {{ form.birth_date.label_tag }} {{ form.birth_date }}
            </div>
            <div class="form-group">
                {{ form.phone_number.label_tag }} {{ form.phone_number }}
            </div>
            <div class="form-group">
                {{ form.country.label_tag }} {{ form.country }}
            </div>
            <div class="form-group">
                {{ form.city.label_tag }} {{ form.city }}
            </div>
            <div class="form-group">
                <label for="{{ form.avatar.id_for_label }}">Загрузить новый аватар</label>
                <input type="file" name="{{ form.avatar.name }}" class="form-control-file" id="{{ form.avatar.id_for_label }}">
            </div>

            <button type="submit">Сохранить изменения</button>
        </form>
        <a href="{% url 'password_change' %}" class="change-password-link">Изменить пароль</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<style>
    .container {
        margin-top: 50px;
        display: flex;
        justify-content: center;
    }
    .card {
        background-color: #fff; /* Белый цвет фона */
        color: #333; /* Цвет текста */
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
        width: 100%;
        max-width: 600px;
    }
    h2 {
        text-align: center;
        font-size: 2.5em;
        font-weight: 300;
        color: #333;
        margin-bottom: 20px;
    }
    .tab {
        display: flex;
        justify-content: center;
        margin-bottom: 20px;
    }
    .tab button {
        background-color: #f1f1f1;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: background-color 0.3s;
        font-size: 1.2em;
        color: #555;
        margin: 0 5px;
        border-radius: 5px;
    }
    .tab button:hover {
        background-color: #ddd;
    }
    .tab button.active {
        background-color: #007bff;
        color: white;
    }
    .tabcontent {
        display: none;
        padding: 20px;
        border-top: none;
        background-color: #fff; /* Белый цвет фона */
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
        color: #333; /* Цвет текста */
    }
    .tabcontent form {
        width: 100%;
    }
    .tabcontent form .form-group {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        margin-bottom: 15px;
    }
    .tabcontent form .form-group label {
        width: 100%;
        text-align: left;
        margin-bottom: 5px;
    }
    .tabcontent form .form-group input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    .tabcontent form button {
        background-color: #007bff;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.2em;
        transition: background-color 0.3s;
        margin-top: 20px;
        display: block;
        width: 100%;
    }
    .tabcontent form button:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <h2>Регистрация</h2>
        <div class="tab">
            <button class="tablinks" onclick="openTab(event, 'patient')">Пациент</button>
            <button class="tablinks" onclick="openTab(event, 'specialist')">Специалист</button>
        </div>

        <div id="patient" class="tabcontent">
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                {% for field in patient_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input type="hidden" name="patient" value="true">
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>

        <div id="specialist" class="tabcontent">
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                {% for field in specialist_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input type="hidden" name="specialist" value="true">
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>

<script>
    function openTab(evt, tabName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(tabName).style.display = "block";
        evt.currentTarget.className += " active";
    }
    // Open the default tab
    document.getElementsByClassName("tablinks")[0].click();
</script>
{% endblock %}